name: Check for new informe epidemiologico

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for new informe epidemiologico
        id: informe_check
        run: |
          cd informe_checker
          python informe_checker.py
        continue-on-error: true

      - name: Create Issue
        if: ${{ steps.informe_check.outcome == 'success' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/NEW_INFORME_ISSUE.md
